# Generated by Django 3.2.4 on 2021-06-23 22:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_cart_carty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carty',
            new_name='Cart',
        ),
    ]
