# Generated by Django 3.2.4 on 2021-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Packed', 'Packed')], default='Pending', max_length=10),
        ),
    ]
